name: Upload Portfolio Content to S3

on:
  push:
    paths:
      - 'data/dynamic_content/**'

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::996385806727:role/github-actions-access
          aws-region: eu-west-1

      - name: Upload to S3 with Standard-IA
        run: |
          aws s3 sync data/dynamic_content s3://ishani-kathuria-website-content \
            --acl public-read \
            --storage-class STANDARD_IA \
            --cache-control "no-store" \
            --delete
